name: Build and Release

on:
  push:
    branches:
      - master
      - github-actions-integration
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: "${{ runner.os }}-buildx-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/workflows/Dockerfile
          push: true
          tags: ghcr.io/psychosoc1al/py-client-server-test-task:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Create output directories
        run: mkdir -p dist

      - name: Build client binary
        run: >-
          docker run --rm -v ${{ github.workspace }}:/app ghcr.io/psychosoc1al/py-client-server-test-task:latest
          bash -c "pyinstaller 
          --clean
          --onefile
          --add-data=.env:.
          --add-data=icons/client.ico:icons
          src/client.py"

      - name: Build server binary
        run: >-
          docker run --rm -v ${{ github.workspace }}:/app ghcr.io/psychosoc1al/py-client-server-test-task:latest
          bash -c "pyinstaller 
          --clean
          --onefile
          --add-data=.env:.
          --add-data=icons/server.ico:icons
          src/server.py"

      - name: Upload release assets
        id: upload-release
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            dist/client
            dist/server

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: dist

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=tag::$latest_tag"

      - name: Increment tag
        id: increment_tag
        run: |
          latest_tag=${{ steps.get_latest_tag.outputs.tag }}
          if [[ $latest_tag == "" ]]; then
            new_tag="v1.0.0"
          else
            IFS='.' read -r -a tag_parts <<< "${latest_tag/v/}"
            major=${tag_parts[0]}
            minor=${tag_parts[1]}
            patch=${tag_parts[2]}
            new_patch=$((patch + 1))
            new_tag="v${major}.${minor}.${new_patch}"
          fi
          echo "New tag: $new_tag"
          echo "::set-output name=new_tag::$new_tag"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.increment_tag.outputs.new_tag }}
          release_name: Release ${{ steps.increment_tag.outputs.new_tag }}
          draft: false
          prerelease: false

      - name: Upload client binary to release
        id: upload_client_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/client
          asset_name: client
          asset_content_type: application/octet-stream

      - name: Upload server binary to release
        id: upload_server_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/server
          asset_name: server
          asset_content_type: application/octet-stream
